meta_product_name: "Chavanne & Witt Avocats"
meta_title: "Chavanne & Witt Avocats"
meta_description: "Secrétaires de la Conférence en 2015, Clémence Witt et Matthieu Chavanne ont décidé de créer le cabinet Chavanne & Witt Avocats en septembre 2017."
meta_image: "banner.png"                           # Une image dans votre dossier app/assets/images/
