meta_product_name: 'Siano Avocats'
meta_title: 'Siano Avocats'
meta_description: 'Né de la fusion de deux structures partageant des valeurs communes, Siano est un cabinet d’avocats présent à Paris et à Barcelone, intervenant dans tous les domaines du droit pénal'
meta_image: 'banner.jpg' # Une image dans votre dossier app/assets/images/
